server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://139.224.64.113:9002/myDataBase?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Qjw18902161911!

mybatis:
  mapper-locations: classpath*:mapper/*.xml


